### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ysumath1** [glemaitre/protoclass#23]
Hi,
My name is Yohan; I am computer vision researcher at US National Institute's of Health. Read your paper about normalization of T2W-MRI for prostate cancer. My lab and I are trying to do a multi-site analysis of prostate MRI images to develop a CAD software for cancer diagnosis. We would to test the robustness of the Rician normalization process, because different sites have vastly different intensity mappings, and we need something robust to pass to our CAD.

I had many problems installing your module in Ubuntu 14.4 with Anaconda <http://glemaitre.github.io/protoclass/install.html>. Edited the pyFFTW setup.py file to use the correct path to the Eigen3 folder, as this is not included with the package. Your instructions for installing the scikit-learn module in your folder do not work; there is a problem with GIL in Cython.

Anyways, I have scikit-learn already, because it ships with Anaconda. Did the main installation in Protoclass root folder; worked okay. Tried `make test` command. This failed many times. First, because `nmrglue` is a required package, but is not included nor mentioned. After installing this via Anaconda, error ensues because your `make test` code cannot find module `proc_autophase`. That is a function (or submodule) in nmrglue, so my gut feeling is there is an error in your test code. 

If possible, please update dependencies, installation guide, test code, and other updates for this package. It seems like it could be quite useful if it can be run outside your institution.
- Yohan

**Comment by glemaitre** [comment]
It is true that the documentation is lagging since I am not working anymore on the package.
But don't worry, the code should still be fine. To install the different part you can do the following

```bash
$ sudo apt-get install libfftw3-dev libfftw3-3 eigen3 (or eigensoft depending of your ubuntu version)
```

It is better to create some python 2 environment since it was develop before that I had some concern about python 2 or python 3 and some third-party are only python 2 compatible

```bash
conda create --name protoclass python=2.7
```

Accept the different install package

```bash
source activate protoclass
```

then install the following package (most of them using conda and the other using pip or the source)

```bash
conda install statsmodel scikit-image scikit-learn mahotas cython ipython -c conda-forge
conda install SimpleITK -c simpleitk
pip install nmrglue

git clone git@github.com:hoytak/pyksvd.git
cd pyksvd
pip install .

cd ../
git clone git@github.com:glemaitre/protoclass.git
cd protoclass
pip install .
```

Then I think that you should be good to go.
You can try to import the following line in python

```python
from protoclass.preprocessing import RicianNormalization
```

and it should not through you some error

**Comment by glemaitre** [comment]
You can also find some code showing the usage for the normalization [there](https://github.com/I2Cvb/mp-mri-prostate/tree/master/pipeline/feature-normalization)

**Comment by ysumath1** [comment]
Okay, I will try this tomorrow (EDT) and let you know how is goes.

- Yohan

**Comment by ysumath1** [comment]
Hi Guillaume,

Thanks for the help. I got the package to work. Please note in
documentation you require nmrglue version >=0.6; conda nmrglue is version
0.5. I downloaded nmrglue 0.6 and installed from source. I don't know what
version pip has.

On a separate note, do you have code showing how to build and apply Rician
normalization to an image, and extracting numpy array for the newly
normalized image? This will be very helpful for the research I am doing at
the NIH and the prostate CAD system we are presently developing.
Thanks,
- Yohan

**Comment by sedghi** [comment]
When i want to install pyksvd i get the following error
```
ksvd/ksvd.hpp:17:44: fatal error: ../third-party/eigen/Eigen/Dense: No such file or directory
    compilation terminated.
```
I have installed eigen for my ubuntu machine
any comment is appreciated

**Comment by sedghi** [comment]
I found the solution
For any one that gets the same error you need to change 
``#include ../third-party/eigen/Eigen/Dense`` in ksvd.hpp file to the path of your Eigen. mine: `#include "/usr/include/eigen3/Eigen/Dense"`
